/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

import aoc.solutions.*

fun main() {
    solveDayOne()
    solveDayTwo()
    solveDayThree()
    solveDayFour()
    solveDayFive()
    solveDaySix()
    solveDaySeven()
    solveDayEight()
    solveDayNine()
    solveDayTen()
    solveDayEleven()
    solveDayTwelve()
    solveDayThirteen()
    solveDayFourteen()
    solveDayFifteen()
    solveDaySixteen()
    solveDaySeventeen()
    solveDayEightteen()
    solveDayNineteen()
    solveDayTwenty()
    solveDayTwentyOne()
    solveDayTwentyTwo()
    solveDayTwentyThree()
    solveDayTwentyFour()
    solveDayTwentyFive()
}
