/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

import aoc.solutions.solveDayTen

fun main() {
//    solveDayOne()
//    solveDayTwo()
//    solveDayThree()
//    solveDayFour()
//    solveDayFive()
//    solveDaySix()
//    solveDaySeven()
//    solveDayEight()
//    solveDayNine()
    solveDayTen()
}
