/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc2016;

// import aoc2016.solutions.Day1;
// import aoc2016.solutions.Day2;
// import aoc2016.solutions.Day3;
// import aoc2016.solutions.Day4;
import aoc2016.solutions.Day5;

public class App {
    public static void main(String[] args) {
        // Day1.solve();
        // Day2.solve();
        // Day3.solve();
        // Day4.solve();
        Day5.solve();
    }
}
