/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc2016;

import aoc2016.solutions.Day1;

public class App {
    public static void main(String[] args) {
        Day1.solve();
    }
}
