pub mod day_1;
pub mod day_10;
pub mod day_11;
pub mod day_12;
pub mod day_13;
pub mod day_14;
pub mod day_15;
pub mod day_16;
pub mod day_17;
pub mod day_18;
pub mod day_19;
pub mod day_2;
pub mod day_20;
pub mod day_21;
pub mod day_22;
pub mod day_23;
pub mod day_24;
pub mod day_25;
pub mod day_3;
pub mod day_4;
pub mod day_5;
pub mod day_6;
pub mod day_7;
pub mod day_8;
pub mod day_9;

fn main() {
    day_1::solve_day_one();
    day_2::solve_day_two();
    day_3::solve_day_3();
    day_4::solve_day_four();
    day_5::solve_day_five();
    day_6::solve_day_six();
    day_7::solve_day_seven();
    day_8::solve_day_eight();
    day_9::solve_day_nine();
    day_10::solve_day_ten();
    day_11::solve_day_eleven();
    day_12::solve_day_twelve();
    day_13::solve_day_13();
    day_14::solve_day_14();
    day_15::solve_day_15();
    day_16::solve_day_16();
    day_17::solve_day_17();
    day_18::solve_day_18();
    day_19::solve_day_19();
    day_20::solve_day_20();
    day_21::solve_day_21();
    day_22::solve_day_22();
    day_23::solve_day_23();
    day_24::solve_day_24();
    day_25::solve_day_25();
}
